version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    # environment:
    #   POSTGRES_HOST: db
    #   POSTGRES_DB: your_database_name
    #   POSTGRES_USER: your_username
    #   POSTGRES_PASSWORD: your_password
    # depends_on:
    #   - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: your_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
